version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ssi_network

  api_server:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - ssi_network

  axiom_model_worker:
    build:
      context: ./axiom_model_worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - ssi_network
    volumes:
      - ./axiom_model_worker/knowledge_base:/app/knowledge_base:ro

  admin_ui:
    build:
      context: ./admin_ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - ssi_network

volumes:
  redis_data:

networks:
  ssi_network:
    driver: bridge
